version: '3.7'

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.13
  entrypoint: ["bash"]
  working_dir: /parcel-plug
  volumes:
    - .:/parcel-plug:cached
    - ./node_modules:/parcel-plug/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  commands:
    <<: *node
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  mongodb:
    tty: true
    image: mongo:3.6
    volumes:
      - mongodb:/data/db
    ports:
      - "11001:27017"

  redis:
    image: redis:alpine
    ports:
      - "11003:6379"

  delivery:
    <<: *node
    working_dir: /parcel-plug/services/delivery
    entrypoint: ["/parcel-plug/node_modules/.bin/gulp"]
    environment:
      <<: *env
      INTERNAL_PORT: 80
      EXTERNAL_PORT: 11004
      ACCOUNT_KEY: ${ACCOUNT_KEY-devel}
      MONGO_DSN: ${MONGO_DSN-mongodb://mongodb:27017/parcel-plug}
    depends_on:
      - mongodb
    ports:
      - "11004:80"

  graphql:
    <<: *node
    working_dir: /parcel-plug/services/graphql
    entrypoint: ["/parcel-plug/node_modules/.bin/gulp"]
    environment:
      <<: *env
      INTERNAL_PORT: 80
      EXTERNAL_PORT: 11002
      ACCOUNT_KEY: ${ACCOUNT_KEY-devel}
      MONGO_DSN: ${MONGO_DSN-mongodb://mongodb:27017/parcel-plug}
      REDIS_DSN: redis://redis:6379/0
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - mongodb
      - redis
    ports:
      - "11002:80"

  manage:
    <<: *node
    image: danlynn/ember-cli:3.6.1
    working_dir: /parcel-plug/services/manage
    entrypoint: ["node_modules/.bin/ember"]
    command: ["serve", "--proxy", "http://graphql"]
    depends_on:
      - graphql
    ports:
      - "4200:4200"
      - "7020:7020"
      - "7357:7357"

volumes:
  mongodb: {}
  yarn-cache: {}
